In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [5]:
import scipy.stats as stats

In [6]:
credit = pd.read_csv('C:/Users/yoosha/Downloads/creditpromo.csv')

In [15]:
diet = pd.read_csv('C:/Users/yoosha/Downloads/dietstudy.csv')

In [16]:
dvd = pd.read_csv('C:/Users/yoosha/Downloads/dvdplayer.csv')

In [17]:
pol = pd.read_csv('C:/Users/yoosha/Downloads/pollination.csv')

In [18]:
samp = pd.read_csv('C:/Users/yoosha/Downloads/sample_survey.csv')

In [19]:
diet.head()

patid  age  gender  tg0  tg1  tg2  tg3  tg4  wgt0  wgt1  wgt2  wgt3  wgt4
0      1   45    Male  180  148  106  113  100   198   196   193   188   192
1      2   56    Male  139   94  119   75   92   237   233   232   228   225
2      3   50    Male  152  185   86  149  118   233   231   229   228   226
3      4   46  Female  112  145  136  149   82   179   181   177   174   172
4      5   64    Male  156  104  157   79   97   219   217   215   213   214

# 1

In [20]:
diet_rel_trigly =  stats.ttest_rel(a = diet.tg0 ,  b = diet.tg4)
diet_rel_trigly

Ttest_relResult(statistic=1.2000008533342437, pvalue=0.24874946576903698)

In [22]:
diet_rel_wt =  stats.ttest_rel(a = diet.wgt0 ,  b = diet.wgt4)
diet_rel_wt

Ttest_relResult(statistic=11.174521688532522, pvalue=1.137689414996614e-08)

In [ ]:
 # Since Triglyceride level has changed, we can infer overall measurement has changed

# 2

In [23]:
credit.head()

id         insert      dollars
0   148       Standard  2232.771979
1   572  New Promotion  1403.807542
2   973       Standard  2327.092181
3  1096       Standard  1280.030541
4  1541  New Promotion  1513.563200

In [28]:
credit['S1'] = credit[credit.insert == 'Standard'] = 0
credit['S2'] = credit[credit.insert == 'New Promotion'] = 1

In [29]:
stats.ttest_rel(a = credit.S1 , b = credit.dollars)

Ttest_relResult(statistic=-101.42608074945085, pvalue=0.0)

In [30]:
stats.ttest_rel(a = credit.S2 , b = credit.dollars)

Ttest_relResult(statistic=-101.36276639598525, pvalue=0.0)

In [ ]:
# Since p value in each case is zero , there is no effective difference in promotions to increase the sales.

# 3

In [31]:
pol.head()

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90

In [32]:
overall_test = stats.ttest_1samp(a = pol.Seed_Yield_Plant, popmean = 200)
overall_test

Ttest_1sampResult(statistic=-2.3009121248548645, pvalue=0.032891040921283025)

In [ ]:
# We can infer that overall population is equal to 200.

In [33]:
pol['N'] = pol.Group[pol.Group == 'Natural'] = 0
pol['H'] = pol.Group[pol.Group == 'Hand'] = 1

C:\Users\yoosha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\yoosha\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [35]:
stats.ttest_rel(a = pol.N , b = pol.Seed_Yield_Plant)

Ttest_relResult(statistic=-21.67129244217419, pvalue=7.368046270487493e-15)

In [36]:
stats.ttest_rel(a = pol.H , b = pol.Seed_Yield_Plant)

Ttest_relResult(statistic=-21.551431419339046, pvalue=8.154801460191006e-15)

In [ ]:
# We can infer that both Natural and Hand pollination are equally effective.

# 4

In [37]:
dvd.head()

agegroup   dvdscore
0  65 and over  38.454803
1        55-64  17.669677
2  65 and over  31.704307
3  65 and over  25.924460
4     Under 25  30.450007

In [38]:
a = pd.crosstab(index = dvd.agegroup , columns = dvd.dvdscore)

In [39]:
stats.chi2_contingency(a)

(340.0,
 0.41373734188694833,
 335,
 array([[0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882, 0.14705882, 0.14705882,
         0.14705882, 0.14705882, 0.14705882],
        [0.17647059, 

In [ ]:
# We can infer that consumers of various ages rated the design differently.

# 5

In [43]:
samp.head()

id            wrkstat        marital  childs   age  educ  paeduc  maeduc  \
0   1  Working full time       Divorced     2.0  60.0  12.0    12.0    12.0   
1   2  Working part-time  Never married     0.0  27.0  17.0    20.0     NaN   
2   3  Working full time        Married     2.0  36.0  12.0    12.0    12.0   
3   4  Working full time  Never married     0.0  21.0  13.0     NaN    12.0   
4   5  Working full time  Never married     0.0  35.0  16.0     NaN    12.0   

   speduc          degree  ...        agecat childcat news1 news2  news3  \
0     NaN     High school  ...      55 to 64      1-2    No    No     No   
1     NaN  Junior college  ...      25 to 34     None    No    No    Yes   
2    16.0     High school  ...      35 to 44      1-2    No    No     No   
3     NaN     High school  ...  Less than 25     None    No    No     No   
4     NaN        Bachelor  ...      35 to 44     None    No    No     No   

  news4 news5      car1      car2      car3  
0    No    No  American  Japanese  Japanese  
1    No    No  American    German  Japanese  
2   Yes   Yes  American  American       NaN  
3   Yes   Yes  American     Other       NaN  
4    No    No  American  American    Korean  

[5 rows x 46 columns]

In [41]:
relation = pd.crosstab(index = samp.wrkstat , columns = samp.marital)

In [42]:
stats.chi2_contingency(relation)

(729.2421426572284,
 1.4875268409067568e-135,
 28,
 array([[ 51.69187279, 155.8869258 ,  76.84240283,  10.77879859,
          32.8       ],
        [  8.51024735,  25.66431095,  12.65088339,   1.7745583 ,
           5.4       ],
        [ 62.09328622, 187.25441696,  92.30459364,  12.94770318,
          39.4       ],
        [ 12.45017668,  37.5459364 ,  18.50777385,   2.59611307,
           7.9       ],
        [  7.24946996,  21.86219081,  10.77667845,   1.51166078,
           4.6       ],
        [  9.14063604,  27.56537102,  13.58798587,   1.90600707,
           5.8       ],
        [246.95477032, 744.74028269, 367.10989399,  51.495053  ,
         156.7       ],
        [ 47.90954064, 144.48056537,  71.21978799,   9.99010601,
          30.4       ]]))

In [ ]:
# We can infer that there is no relation between labour force status with marital status.

In [96]:
edu = pd.crosstab(index = samp.educ , columns = samp.marital)

In [98]:
stats.chi2_contingency(edu)

(221.10896441647762,
 4.3102883499745113e-16,
 76,
 array([[3.15005321e-01, 9.49982263e-01, 4.68251153e-01, 6.59808443e-02,
         2.00780419e-01],
        [7.87513303e-01, 2.37495566e+00, 1.17062788e+00, 1.64952111e-01,
         5.01951046e-01],
        [1.57502661e+00, 4.74991132e+00, 2.34125576e+00, 3.29904221e-01,
         1.00390209e+00],
        [1.41752394e+00, 4.27492018e+00, 2.10713019e+00, 2.96913799e-01,
         9.03511884e-01],
        [1.26002128e+00, 3.79992905e+00, 1.87300461e+00, 2.63923377e-01,
         8.03121674e-01],
        [3.62256119e+00, 1.09247960e+01, 5.38488826e+00, 7.58779709e-01,
         2.30897481e+00],
        [3.30755587e+00, 9.97481376e+00, 4.91663711e+00, 6.92798865e-01,
         2.10819440e+00],
        [1.29152182e+01, 3.89492728e+01, 1.91982973e+01, 2.70521462e+00,
         8.23199716e+00],
        [1.18126995e+01, 3.56243349e+01, 1.75594182e+01, 2.47428166e+00,
         7.52926570e+00],
        [1.77978006e+01, 5.36739979e+01, 2.64561901e+01, 3

In [ ]:
# We can infer that there is no relation between educational qualification with marital status.

In [44]:
hap_1 = pd.crosstab(index = samp.happy , columns = samp.income)

In [45]:
stats.chi2_contingency(hap_1)

(178.9505306121643,
 1.4107677273473057e-26,
 22,
 array([[  3.89520355,  23.12777106,  21.66706973,  29.82265216,
         191.35187424,   2.92140266,   3.89520355,   4.26037888,
           4.01692866,   5.72108021,   7.06005643,   4.26037888],
        [ 18.16041919, 107.82748892, 101.01733172, 139.04070939,
         892.1305925 ,  13.62031439,  18.16041919,  19.86295848,
          18.72793229,  26.67311568,  32.91575977,  19.86295848],
        [  9.94437727,  59.04474002,  55.31559855,  76.13663845,
         488.51753325,   7.45828295,   9.94437727,  10.87666264,
          10.25513906,  14.60580411,  18.0241838 ,  10.87666264]]))

In [46]:
hap_2 = pd.crosstab(index = samp.happy , columns = samp.marital)

In [47]:
stats.chi2_contingency(hap_2)

(260.6894389418282,
 9.3147261197964e-52,
 8,
 array([[ 53.6969697 , 162.06060606,  79.27272727,  11.15151515,
          33.81818182],
        [248.58538324, 750.24527629, 366.98609626,  51.62495544,
         156.55828877],
        [140.71764706, 424.69411765, 207.74117647,  29.22352941,
          88.62352941]]))

In [ ]:
# We can infer that happiness is neither driven by earnings nor by marital status.